apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-rolebinding
  namespace: tenant-a
subjects:
- kind: ServiceAccount
  name: default
  namespace: tenant-a
- kind: User
  name: tenant-a-admin
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: tenant-role
  apiGroup: rbac.authorization.k8s.io
